// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file kujira/cwica/query.proto (package kujira.cwica, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryInterchainAccountRequest, QueryInterchainAccountResponse } from "./query_pb.js";

const TYPE_NAME = "kujira.cwica.Query";

/**
 * QueryInterchainAccount returns the interchain account for given owner address on a given connection pair
 *
 * @generated from rpc kujira.cwica.Query.InterchainAccount
 */
export const QueryInterchainAccountService = {
  typeName: TYPE_NAME,
  method: "InterchainAccount",
  Request: QueryInterchainAccountRequest,
  Response: QueryInterchainAccountResponse,
} as const;

