// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/slashing/v1beta1/tx.proto (package cosmos.slashing.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUnjail, MsgUpdateParams } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.slashing.v1beta1.MsgUnjail": MsgUnjail,
  "cosmos.slashing.v1beta1.MsgUpdateParams": MsgUpdateParams,
};
