// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/core/client/v1/query.proto (package ibc.core.client.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryClientParamsRequest, QueryClientStateRequest, QueryClientStatesRequest, QueryClientStatusRequest, QueryConsensusStateHeightsRequest, QueryConsensusStateRequest, QueryConsensusStatesRequest, QueryUpgradedClientStateRequest, QueryUpgradedConsensusStateRequest } from "./query_pb.js";

export const QueryRegistry = {
  "ibc.core.client.v1.QueryClientState": QueryClientStateRequest,
  "ibc.core.client.v1.QueryClientStates": QueryClientStatesRequest,
  "ibc.core.client.v1.QueryConsensusState": QueryConsensusStateRequest,
  "ibc.core.client.v1.QueryConsensusStates": QueryConsensusStatesRequest,
  "ibc.core.client.v1.QueryConsensusStateHeights": QueryConsensusStateHeightsRequest,
  "ibc.core.client.v1.QueryClientStatus": QueryClientStatusRequest,
  "ibc.core.client.v1.QueryClientParams": QueryClientParamsRequest,
  "ibc.core.client.v1.QueryUpgradedClientState": QueryUpgradedClientStateRequest,
  "ibc.core.client.v1.QueryUpgradedConsensusState": QueryUpgradedConsensusStateRequest,
};
