// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/core/client/v1/tx.proto (package ibc.core.client.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCreateClient, MsgSubmitMisbehaviour, MsgUpdateClient, MsgUpgradeClient } from "./tx_pb.js";

export const MsgRegistry = {
  "ibc.core.client.v1.MsgCreateClient": MsgCreateClient,
  "ibc.core.client.v1.MsgUpdateClient": MsgUpdateClient,
  "ibc.core.client.v1.MsgUpgradeClient": MsgUpgradeClient,
  "ibc.core.client.v1.MsgSubmitMisbehaviour": MsgSubmitMisbehaviour,
};
