// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/applications/interchain_accounts/controller/v1/query.proto (package ibc.applications.interchain_accounts.controller.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryInterchainAccountRequest, QueryParamsRequest } from "./query_pb.js";

export const QueryRegistry = {
  "ibc.applications.interchain_accounts.controller.v1.QueryInterchainAccount": QueryInterchainAccountRequest,
  "ibc.applications.interchain_accounts.controller.v1.QueryParams": QueryParamsRequest,
};
