// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/autocli/v1/query.proto (package cosmos.autocli.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AppOptionsRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.autocli.v1.QueryAppOptions": AppOptionsRequest,
};
