// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/distribution/v1beta1/tx.proto (package cosmos.distribution.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCommunityPoolSpend, MsgFundCommunityPool, MsgSetWithdrawAddress, MsgUpdateParams, MsgWithdrawDelegatorReward, MsgWithdrawValidatorCommission } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.distribution.v1beta1.MsgSetWithdrawAddress": MsgSetWithdrawAddress,
  "cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward": MsgWithdrawDelegatorReward,
  "cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission": MsgWithdrawValidatorCommission,
  "cosmos.distribution.v1beta1.MsgFundCommunityPool": MsgFundCommunityPool,
  "cosmos.distribution.v1beta1.MsgUpdateParams": MsgUpdateParams,
  "cosmos.distribution.v1beta1.MsgCommunityPoolSpend": MsgCommunityPoolSpend,
};
