// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/orm/query/v1alpha1/query.proto (package cosmos.orm.query.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRequest, ListRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.orm.query.v1alpha1.QueryGet": GetRequest,
  "cosmos.orm.query.v1alpha1.QueryList": ListRequest,
};
