// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/vesting/v1beta1/tx.proto (package cosmos.vesting.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCreatePeriodicVestingAccount, MsgCreatePermanentLockedAccount, MsgCreateVestingAccount } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.vesting.v1beta1.MsgCreateVestingAccount": MsgCreateVestingAccount,
  "cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccount": MsgCreatePermanentLockedAccount,
  "cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount": MsgCreatePeriodicVestingAccount,
};
