// Since: cosmos-sdk 0.46

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/group/v1/query.proto (package cosmos.group.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryGroupInfoRequest, QueryGroupMembersRequest, QueryGroupPoliciesByAdminRequest, QueryGroupPoliciesByGroupRequest, QueryGroupPolicyInfoRequest, QueryGroupsByAdminRequest, QueryGroupsByMemberRequest, QueryGroupsRequest, QueryProposalRequest, QueryProposalsByGroupPolicyRequest, QueryTallyResultRequest, QueryVoteByProposalVoterRequest, QueryVotesByProposalRequest, QueryVotesByVoterRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.group.v1.QueryGroupInfo": QueryGroupInfoRequest,
  "cosmos.group.v1.QueryGroupPolicyInfo": QueryGroupPolicyInfoRequest,
  "cosmos.group.v1.QueryGroupMembers": QueryGroupMembersRequest,
  "cosmos.group.v1.QueryGroupsByAdmin": QueryGroupsByAdminRequest,
  "cosmos.group.v1.QueryGroupPoliciesByGroup": QueryGroupPoliciesByGroupRequest,
  "cosmos.group.v1.QueryGroupPoliciesByAdmin": QueryGroupPoliciesByAdminRequest,
  "cosmos.group.v1.QueryProposal": QueryProposalRequest,
  "cosmos.group.v1.QueryProposalsByGroupPolicy": QueryProposalsByGroupPolicyRequest,
  "cosmos.group.v1.QueryVoteByProposalVoter": QueryVoteByProposalVoterRequest,
  "cosmos.group.v1.QueryVotesByProposal": QueryVotesByProposalRequest,
  "cosmos.group.v1.QueryVotesByVoter": QueryVotesByVoterRequest,
  "cosmos.group.v1.QueryGroupsByMember": QueryGroupsByMemberRequest,
  "cosmos.group.v1.QueryTallyResult": QueryTallyResultRequest,
  "cosmos.group.v1.QueryGroups": QueryGroupsRequest,
};
