// Since: cosmos-sdk 0.46

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/group/v1/tx.proto (package cosmos.group.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCreateGroup, MsgCreateGroupPolicy, MsgCreateGroupWithPolicy, MsgExec, MsgLeaveGroup, MsgSubmitProposal, MsgUpdateGroupAdmin, MsgUpdateGroupMembers, MsgUpdateGroupMetadata, MsgUpdateGroupPolicyAdmin, MsgUpdateGroupPolicyDecisionPolicy, MsgUpdateGroupPolicyMetadata, MsgVote, MsgWithdrawProposal } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.group.v1.MsgCreateGroup": MsgCreateGroup,
  "cosmos.group.v1.MsgUpdateGroupMembers": MsgUpdateGroupMembers,
  "cosmos.group.v1.MsgUpdateGroupAdmin": MsgUpdateGroupAdmin,
  "cosmos.group.v1.MsgUpdateGroupMetadata": MsgUpdateGroupMetadata,
  "cosmos.group.v1.MsgCreateGroupPolicy": MsgCreateGroupPolicy,
  "cosmos.group.v1.MsgCreateGroupWithPolicy": MsgCreateGroupWithPolicy,
  "cosmos.group.v1.MsgUpdateGroupPolicyAdmin": MsgUpdateGroupPolicyAdmin,
  "cosmos.group.v1.MsgUpdateGroupPolicyDecisionPolicy": MsgUpdateGroupPolicyDecisionPolicy,
  "cosmos.group.v1.MsgUpdateGroupPolicyMetadata": MsgUpdateGroupPolicyMetadata,
  "cosmos.group.v1.MsgSubmitProposal": MsgSubmitProposal,
  "cosmos.group.v1.MsgWithdrawProposal": MsgWithdrawProposal,
  "cosmos.group.v1.MsgVote": MsgVote,
  "cosmos.group.v1.MsgExec": MsgExec,
  "cosmos.group.v1.MsgLeaveGroup": MsgLeaveGroup,
};
