// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/app/v1alpha1/query.proto (package cosmos.app.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryConfigRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.app.v1alpha1.QueryConfig": QueryConfigRequest,
};
