// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/evidence/v1beta1/query.proto (package cosmos.evidence.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAllEvidenceRequest, QueryEvidenceRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.evidence.v1beta1.QueryEvidence": QueryEvidenceRequest,
  "cosmos.evidence.v1beta1.QueryAllEvidence": QueryAllEvidenceRequest,
};
