// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/evidence/v1beta1/tx.proto (package cosmos.evidence.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgSubmitEvidence } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.evidence.v1beta1.MsgSubmitEvidence": MsgSubmitEvidence,
};
