// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/params/v1beta1/query.proto (package cosmos.params.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QuerySubspacesRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.params.v1beta1.QueryParams": QueryParamsRequest,
  "cosmos.params.v1beta1.QuerySubspaces": QuerySubspacesRequest,
};
