// Since: cosmos-sdk 0.43

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/authz/v1beta1/query.proto (package cosmos.authz.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryGranteeGrantsRequest, QueryGranterGrantsRequest, QueryGrantsRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.authz.v1beta1.QueryGrants": QueryGrantsRequest,
  "cosmos.authz.v1beta1.QueryGranterGrants": QueryGranterGrantsRequest,
  "cosmos.authz.v1beta1.QueryGranteeGrants": QueryGranteeGrantsRequest,
};
