// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/base/tendermint/v1beta1/query.proto (package cosmos.base.tendermint.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ABCIQueryRequest, GetBlockByHeightRequest, GetLatestBlockRequest, GetLatestValidatorSetRequest, GetNodeInfoRequest, GetSyncingRequest, GetValidatorSetByHeightRequest } from "./query_pb.js";

export const ServiceRegistry = {
  "cosmos.base.tendermint.v1beta1.ServiceGetNodeInfo": GetNodeInfoRequest,
  "cosmos.base.tendermint.v1beta1.ServiceGetSyncing": GetSyncingRequest,
  "cosmos.base.tendermint.v1beta1.ServiceGetLatestBlock": GetLatestBlockRequest,
  "cosmos.base.tendermint.v1beta1.ServiceGetBlockByHeight": GetBlockByHeightRequest,
  "cosmos.base.tendermint.v1beta1.ServiceGetLatestValidatorSet": GetLatestValidatorSetRequest,
  "cosmos.base.tendermint.v1beta1.ServiceGetValidatorSetByHeight": GetValidatorSetByHeightRequest,
  "cosmos.base.tendermint.v1beta1.ServiceABCIQuery": ABCIQueryRequest,
};
