// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file kujira/denom/query.proto (package kujira.denom, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryDenomAuthorityMetadataRequest, QueryDenomAuthorityMetadataResponse, QueryDenomsFromCreatorRequest, QueryDenomsFromCreatorResponse, QueryNoFeeAccountsRequest, QueryNoFeeAccountsResponse, QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";

const TYPE_NAME = "kujira.denom.Query";

/**
 * Params returns the total set of minting parameters.
 *
 * @generated from rpc kujira.denom.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * @generated from rpc kujira.denom.Query.DenomAuthorityMetadata
 */
export const QueryDenomAuthorityMetadataService = {
  typeName: TYPE_NAME,
  method: "DenomAuthorityMetadata",
  Request: QueryDenomAuthorityMetadataRequest,
  Response: QueryDenomAuthorityMetadataResponse,
} as const;

/**
 * @generated from rpc kujira.denom.Query.DenomsFromCreator
 */
export const QueryDenomsFromCreatorService = {
  typeName: TYPE_NAME,
  method: "DenomsFromCreator",
  Request: QueryDenomsFromCreatorRequest,
  Response: QueryDenomsFromCreatorResponse,
} as const;

/**
 * NoFeeAccounts returns accounts whitelisted to create denom without fee
 *
 * @generated from rpc kujira.denom.Query.NoFeeAccounts
 */
export const QueryNoFeeAccountsService = {
  typeName: TYPE_NAME,
  method: "NoFeeAccounts",
  Request: QueryNoFeeAccountsRequest,
  Response: QueryNoFeeAccountsResponse,
} as const;

