// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file kujira/denom/tx.proto (package kujira.denom, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAddNoFeeAccounts, MsgAddNoFeeAccountsResponse, MsgBurn, MsgBurnResponse, MsgChangeAdmin, MsgChangeAdminResponse, MsgCreateDenom, MsgCreateDenomResponse, MsgMint, MsgMintResponse, MsgRemoveNoFeeAccounts, MsgRemoveNoFeeAccountsResponse } from "./tx_pb.js";

const TYPE_NAME = "kujira.denom.Msg";

/**
 * @generated from rpc kujira.denom.Msg.AddNoFeeAccounts
 */
export const MsgAddNoFeeAccountsService = {
  typeName: TYPE_NAME,
  method: "AddNoFeeAccounts",
  Request: MsgAddNoFeeAccounts,
  Response: MsgAddNoFeeAccountsResponse,
} as const;

/**
 * @generated from rpc kujira.denom.Msg.RemoveNoFeeAccounts
 */
export const MsgRemoveNoFeeAccountsService = {
  typeName: TYPE_NAME,
  method: "RemoveNoFeeAccounts",
  Request: MsgRemoveNoFeeAccounts,
  Response: MsgRemoveNoFeeAccountsResponse,
} as const;

/**
 * @generated from rpc kujira.denom.Msg.CreateDenom
 */
export const MsgCreateDenomService = {
  typeName: TYPE_NAME,
  method: "CreateDenom",
  Request: MsgCreateDenom,
  Response: MsgCreateDenomResponse,
} as const;

/**
 * @generated from rpc kujira.denom.Msg.Mint
 */
export const MsgMintService = {
  typeName: TYPE_NAME,
  method: "Mint",
  Request: MsgMint,
  Response: MsgMintResponse,
} as const;

/**
 * @generated from rpc kujira.denom.Msg.Burn
 */
export const MsgBurnService = {
  typeName: TYPE_NAME,
  method: "Burn",
  Request: MsgBurn,
  Response: MsgBurnResponse,
} as const;

/**
 * ForceTransfer is deactivated for now because we need to think through edge
 * cases rpc ForceTransfer(MsgForceTransfer) returns
 * (MsgForceTransferResponse);
 *
 * @generated from rpc kujira.denom.Msg.ChangeAdmin
 */
export const MsgChangeAdminService = {
  typeName: TYPE_NAME,
  method: "ChangeAdmin",
  Request: MsgChangeAdmin,
  Response: MsgChangeAdminResponse,
} as const;

