// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/mint/v1beta1/query.proto (package cosmos.mint.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAnnualProvisionsRequest, QueryInflationRequest, QueryParamsRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.mint.v1beta1.QueryParams": QueryParamsRequest,
  "cosmos.mint.v1beta1.QueryInflation": QueryInflationRequest,
  "cosmos.mint.v1beta1.QueryAnnualProvisions": QueryAnnualProvisionsRequest,
};
