// Since: cosmos-sdk 0.43

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/feegrant/v1beta1/query.proto (package cosmos.feegrant.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAllowanceRequest, QueryAllowancesByGranterRequest, QueryAllowancesRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.feegrant.v1beta1.QueryAllowance": QueryAllowanceRequest,
  "cosmos.feegrant.v1beta1.QueryAllowances": QueryAllowancesRequest,
  "cosmos.feegrant.v1beta1.QueryAllowancesByGranter": QueryAllowancesByGranterRequest,
};
