// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/applications/fee/v1/query.proto (package ibc.applications.fee.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryCounterpartyPayeeRequest, QueryFeeEnabledChannelRequest, QueryFeeEnabledChannelsRequest, QueryIncentivizedPacketRequest, QueryIncentivizedPacketsForChannelRequest, QueryIncentivizedPacketsRequest, QueryPayeeRequest, QueryTotalAckFeesRequest, QueryTotalRecvFeesRequest, QueryTotalTimeoutFeesRequest } from "./query_pb.js";

export const QueryRegistry = {
  "ibc.applications.fee.v1.QueryIncentivizedPackets": QueryIncentivizedPacketsRequest,
  "ibc.applications.fee.v1.QueryIncentivizedPacket": QueryIncentivizedPacketRequest,
  "ibc.applications.fee.v1.QueryIncentivizedPacketsForChannel": QueryIncentivizedPacketsForChannelRequest,
  "ibc.applications.fee.v1.QueryTotalRecvFees": QueryTotalRecvFeesRequest,
  "ibc.applications.fee.v1.QueryTotalAckFees": QueryTotalAckFeesRequest,
  "ibc.applications.fee.v1.QueryTotalTimeoutFees": QueryTotalTimeoutFeesRequest,
  "ibc.applications.fee.v1.QueryPayee": QueryPayeeRequest,
  "ibc.applications.fee.v1.QueryCounterpartyPayee": QueryCounterpartyPayeeRequest,
  "ibc.applications.fee.v1.QueryFeeEnabledChannels": QueryFeeEnabledChannelsRequest,
  "ibc.applications.fee.v1.QueryFeeEnabledChannel": QueryFeeEnabledChannelRequest,
};
