// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/applications/fee/v1/tx.proto (package ibc.applications.fee.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgPayPacketFee, MsgPayPacketFeeAsync, MsgRegisterCounterpartyPayee, MsgRegisterPayee } from "./tx_pb.js";

export const MsgRegistry = {
  "ibc.applications.fee.v1.MsgRegisterPayee": MsgRegisterPayee,
  "ibc.applications.fee.v1.MsgRegisterCounterpartyPayee": MsgRegisterCounterpartyPayee,
  "ibc.applications.fee.v1.MsgPayPacketFee": MsgPayPacketFee,
  "ibc.applications.fee.v1.MsgPayPacketFeeAsync": MsgPayPacketFeeAsync,
};
