// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/auth/v1beta1/tx.proto (package cosmos.auth.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdateParams } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.auth.v1beta1.MsgUpdateParams": MsgUpdateParams,
};
