// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/base/node/v1beta1/query.proto (package cosmos.base.node.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ConfigRequest } from "./query_pb.js";

export const ServiceRegistry = {
  "cosmos.base.node.v1beta1.ServiceConfig": ConfigRequest,
};
