// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/gov/v1beta1/query.proto (package cosmos.gov.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryDepositRequest, QueryDepositsRequest, QueryParamsRequest, QueryProposalRequest, QueryProposalsRequest, QueryTallyResultRequest, QueryVoteRequest, QueryVotesRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.gov.v1beta1.QueryProposal": QueryProposalRequest,
  "cosmos.gov.v1beta1.QueryProposals": QueryProposalsRequest,
  "cosmos.gov.v1beta1.QueryVote": QueryVoteRequest,
  "cosmos.gov.v1beta1.QueryVotes": QueryVotesRequest,
  "cosmos.gov.v1beta1.QueryParams": QueryParamsRequest,
  "cosmos.gov.v1beta1.QueryDeposit": QueryDepositRequest,
  "cosmos.gov.v1beta1.QueryDeposits": QueryDepositsRequest,
  "cosmos.gov.v1beta1.QueryTallyResult": QueryTallyResultRequest,
};
