// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/gov/v1beta1/tx.proto (package cosmos.gov.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgDeposit, MsgSubmitProposal, MsgVote, MsgVoteWeighted } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.gov.v1beta1.MsgSubmitProposal": MsgSubmitProposal,
  "cosmos.gov.v1beta1.MsgVote": MsgVote,
  "cosmos.gov.v1beta1.MsgVoteWeighted": MsgVoteWeighted,
  "cosmos.gov.v1beta1.MsgDeposit": MsgDeposit,
};
