// Since: cosmos-sdk 0.46

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/gov/v1/tx.proto (package cosmos.gov.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgDeposit, MsgExecLegacyContent, MsgSubmitProposal, MsgUpdateParams, MsgVote, MsgVoteWeighted } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.gov.v1.MsgSubmitProposal": MsgSubmitProposal,
  "cosmos.gov.v1.MsgExecLegacyContent": MsgExecLegacyContent,
  "cosmos.gov.v1.MsgVote": MsgVote,
  "cosmos.gov.v1.MsgVoteWeighted": MsgVoteWeighted,
  "cosmos.gov.v1.MsgDeposit": MsgDeposit,
  "cosmos.gov.v1.MsgUpdateParams": MsgUpdateParams,
};
