// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file tendermint/abci/types.proto (package tendermint.abci, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RequestApplySnapshotChunk, RequestBeginBlock, RequestCheckTx, RequestCommit, RequestDeliverTx, RequestEcho, RequestEndBlock, RequestFlush, RequestInfo, RequestInitChain, RequestListSnapshots, RequestLoadSnapshotChunk, RequestOfferSnapshot, RequestPrepareProposal, RequestProcessProposal, RequestQuery } from "./types_pb.js";

export const ABCIApplicationRegistry = {
  "tendermint.abci.ABCIApplicationEcho": RequestEcho,
  "tendermint.abci.ABCIApplicationFlush": RequestFlush,
  "tendermint.abci.ABCIApplicationInfo": RequestInfo,
  "tendermint.abci.ABCIApplicationDeliverTx": RequestDeliverTx,
  "tendermint.abci.ABCIApplicationCheckTx": RequestCheckTx,
  "tendermint.abci.ABCIApplicationQuery": RequestQuery,
  "tendermint.abci.ABCIApplicationCommit": RequestCommit,
  "tendermint.abci.ABCIApplicationInitChain": RequestInitChain,
  "tendermint.abci.ABCIApplicationBeginBlock": RequestBeginBlock,
  "tendermint.abci.ABCIApplicationEndBlock": RequestEndBlock,
  "tendermint.abci.ABCIApplicationListSnapshots": RequestListSnapshots,
  "tendermint.abci.ABCIApplicationOfferSnapshot": RequestOfferSnapshot,
  "tendermint.abci.ABCIApplicationLoadSnapshotChunk": RequestLoadSnapshotChunk,
  "tendermint.abci.ABCIApplicationApplySnapshotChunk": RequestApplySnapshotChunk,
  "tendermint.abci.ABCIApplicationPrepareProposal": RequestPrepareProposal,
  "tendermint.abci.ABCIApplicationProcessProposal": RequestProcessProposal,
};
