// Since: cosmos-sdk 0.43

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/base/reflection/v2alpha1/reflection.proto (package cosmos.base.reflection.v2alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAuthnDescriptorRequest, GetChainDescriptorRequest, GetCodecDescriptorRequest, GetConfigurationDescriptorRequest, GetQueryServicesDescriptorRequest, GetTxDescriptorRequest } from "./reflection_pb.js";

export const ReflectionServiceRegistry = {
  "cosmos.base.reflection.v2alpha1.ReflectionServiceGetAuthnDescriptor": GetAuthnDescriptorRequest,
  "cosmos.base.reflection.v2alpha1.ReflectionServiceGetChainDescriptor": GetChainDescriptorRequest,
  "cosmos.base.reflection.v2alpha1.ReflectionServiceGetCodecDescriptor": GetCodecDescriptorRequest,
  "cosmos.base.reflection.v2alpha1.ReflectionServiceGetConfigurationDescriptor": GetConfigurationDescriptorRequest,
  "cosmos.base.reflection.v2alpha1.ReflectionServiceGetQueryServicesDescriptor": GetQueryServicesDescriptorRequest,
  "cosmos.base.reflection.v2alpha1.ReflectionServiceGetTxDescriptor": GetTxDescriptorRequest,
};
