// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/core/channel/v1/tx.proto (package ibc.core.channel.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAcknowledgement, MsgChannelCloseConfirm, MsgChannelCloseInit, MsgChannelOpenAck, MsgChannelOpenConfirm, MsgChannelOpenInit, MsgChannelOpenTry, MsgRecvPacket, MsgTimeout, MsgTimeoutOnClose } from "./tx_pb.js";

export const MsgRegistry = {
  "ibc.core.channel.v1.MsgChannelOpenInit": MsgChannelOpenInit,
  "ibc.core.channel.v1.MsgChannelOpenTry": MsgChannelOpenTry,
  "ibc.core.channel.v1.MsgChannelOpenAck": MsgChannelOpenAck,
  "ibc.core.channel.v1.MsgChannelOpenConfirm": MsgChannelOpenConfirm,
  "ibc.core.channel.v1.MsgChannelCloseInit": MsgChannelCloseInit,
  "ibc.core.channel.v1.MsgChannelCloseConfirm": MsgChannelCloseConfirm,
  "ibc.core.channel.v1.MsgRecvPacket": MsgRecvPacket,
  "ibc.core.channel.v1.MsgTimeout": MsgTimeout,
  "ibc.core.channel.v1.MsgTimeoutOnClose": MsgTimeoutOnClose,
  "ibc.core.channel.v1.MsgAcknowledgement": MsgAcknowledgement,
};
