// Since: cosmos-sdk 0.47

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/consensus/v1/query.proto (package cosmos.consensus.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest } from "./query_pb.js";

export const QueryRegistry = {
  "cosmos.consensus.v1.QueryParams": QueryParamsRequest,
};
