// Since: cosmos-sdk 0.46

// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file cosmos/upgrade/v1beta1/tx.proto (package cosmos.upgrade.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCancelUpgrade, MsgSoftwareUpgrade } from "./tx_pb.js";

export const MsgRegistry = {
  "cosmos.upgrade.v1beta1.MsgSoftwareUpgrade": MsgSoftwareUpgrade,
  "cosmos.upgrade.v1beta1.MsgCancelUpgrade": MsgCancelUpgrade,
};
