// @generated by protoc-gen-ts-protobuf-any v0.0.2 with parameter "target=ts"
// @generated from file ibc/applications/interchain_accounts/host/v1/tx.proto (package ibc.applications.interchain_accounts.host.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgModuleQuerySafe } from "./tx_pb.js";

export const MsgRegistry = {
  "ibc.applications.interchain_accounts.host.v1.MsgModuleQuerySafe": MsgModuleQuerySafe,
};
